### ISSUE TITLE
Rendered `Source Code` buttons should point to generated repo's code

### ISSUE THREAD

**Issue by ethanmsl** [ethanmsl/cargo_generate_eframe_template#4]
<img width="445" alt="source link not being updated" src="https://github.com/ethanmsl/cargo_generate_eframe_template/assets/33399972/a005a962-69da-4b51-9a1d-7405caed2431">

This code is pointing to a canonical source.  Rather than our local repo.
(In this example the source is the same, but obviously would diverge on use.)

Commit-fixed link to:
- Above repo, generated from this one with cargo-generate : [etest/...bda93](https://github.com/ethanmsl/etest/tree/ba298278d54727ac7298d060c548d32771dbda93)
- Corresponding static site (since this is stored as an independent branch on the repo): [etest-gh-pages/...ae243](https://github.com/ethanmsl/cargo_generate_eframe_template/tree/3a857b7ab5d9109e9ef77ee0b1bdab5709dae243)

**Comment by dream-dasher** [comment]
Fixed: [commit/...8bf06](https://github.com/ethanmsl/cargo_generate_eframe_template/commit/e650a314cff7ba9ef5877984fc5279cbb558bf06)
